clock_offset: 0.0 # s, approximately
node_distance: 2.127 # m
message_interval: 1.2e-2 # s
message_measure: # how many messages sent per node alternatively
- 1 # node 0x00
- 1 # node 0x01
tx_antenna_delay: 0 # us
rx_antenna_delay: 0 # us
rx_timeout: 10000 # us
preamble_timeout: 16000 # us, deactivated if commented
nodes:
- 0x00 # /dev/ttyACM0
- 0x01 # /dev/ttyACM1
node_pairs:
  - nodes:
    - 0x00
    - 0x01
    distance: 2.127 # m
temperature: # deg C
- 21.2 # node 0x00
- 20.7 # node 0x01
K: 2000
preamble_length: 256
post_processing:
  K: 500  # Number of messages used for joint ranging and timing
  B: 50   # Number of bins generated
note: wire inbetween from node 0x01