clock_offset: 0.0 # s, approximately
node_distance: 0.256 # m
message_interval: 8e-3 # s
message_measure: # how many messages sent per node alternatively
- 1 # node 0x00
- 1 # node 0x01
tx_antenna_delay: 0 # us
rx_antenna_delay: 0 # us
rx_timeout: 10000 # us
preamble_timeout: 0 # us, deactivated if commented
nodes:
- 0x00 # /dev/ttyACM0
- 0x01 # /dev/ttyACM1
temperature: # deg C
- 32.3 # node 0x00
- 28.8 # node 0x01
K: 3000
preamble_length: 128